### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by anthony-chaudhary** [udacity/simple_arm#3]
Running in Udacity provided VMware.

Gazebo works if I load it without simple_arm

![image](https://user-images.githubusercontent.com/18080164/29746553-ed806884-8a9a-11e7-8148-aa84a763de16.png)

![3c6a28e6a57ffdf8d5de96d68985ce01007e4f29](https://user-images.githubusercontent.com/18080164/29746552-e7372e9a-8a9a-11e7-96f9-b06b362f2227.png)

**Comment by kylesf** [comment]
Please try with VM version 2.1 and try the solution proposed in the pull requests.

**Comment by anthony-chaudhary** [comment]
Thanks Kyle!
And thank you: https://github.com/adammalpass
As Adam suggested:


Adding a new file named: `safe_spawner.sh` with:

```
#! /bin/bash
# This script safely launches ros nodes with buffer time to allow arm_mover service to start up in time
x-terminal-emulator -e roslaunch simple_arm robot_spawn.launch &
sleep 5 &&
x-terminal-emulator -e ./look_away
```

Fixed it for me

**Comment by bharatbobba** [comment]
@kylesf Do you have a link to the VM version 2.1?

**Comment by bharatbobba** [comment]
@kylesf Do you have a link to the VM version 2.1?

**Comment by kylesf** [comment]
It can be found in the classroom.

**Comment by AnkS4** [comment]
@kylesf I can only find VM Version 1.0 in the classroom.
How else can I get link to VM 2.1?
